baseURL = "http://samedwardsmarsh.com"
languageCode = "en-us"
title = "Sam Edwards-Marsh"
theme = "hugo-coder"

# Theme parameters
[params]
    author = "Sam Edwards-Marsh"
    info = "Computer Science B.S. Student at UCSC"
    description = "Sam Edwards-Marsh's personal site"
    keywords = "blog,developer,personal,project"
    avatarURL = "avatar.jpeg"
    favicon_16 = "favicon-16x16.png"
    favicon_32 = "favicon-32x32.png"
    touchIcon = "apple-touch-icon.png"

# Menu items
[[menu.main]]
    name = "Projects"
    weight = 1
    url  = "projects/"
[[menu.main]]
    name = "Resume"
    weight = 2
    url = "resume/"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github fa-2x"
    weight = 1
    url = "https://github.com/sedwardsmarsh"
[[params.social]]
    name = "Linkedin"
    icon = "fa fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/samuel-e-31b34a121/"